### PR TITLE
Merged martenson/disposable-email-domains blacklist

### PR DESCRIPTION
**Pull request by mipapo**
Just asked the Martenson if I could merge the blacklist, because his one is a bit better ;)
https://github.com/martenson/disposable-email-domains/issues/15

### CODE REVIEW

**Comment by nojacko** [comment]
Good work. Although, yahoo.com.ph and yahoo.com.vn seem to be valid Yahoo! domains. I wouldn't consider them to be disposable any more than a yahoo.com or gmail.com address.

**Comment by martenson** [comment]
@nojacko good catch, added them to whitelist

**Comment by martenson** [comment]
They are now removed from the list: https://github.com/martenson/disposable-email-domains/commit/7ecfdaee44fe4b5832fda959a168de0897894c7f

**Comment by nojacko** [comment]
Thanks for the pull request. I'm not going to merge it as it's prompted me to finish my disposable email library https://github.com/nojacko/email-data-disposable which pulls in https://github.com/martenson/disposable-email-domains  (along with several other sources) and whitelists a lot more common domains. It loads it in via composer which, as a compose based project, I prefer over a submodule or manually updating.

**Pull request closed without merging**
